### ISSUE TITLE
"values" should be expressed as "constraints"/"enum"

### ISSUE THREAD

**Issue by danfowler** [openreferral/specification#100]
We can now specify that a given column must be one of several values in core JSON Table Schema.  We can use the "enum" constraint for this: 

http://specs.frictionlessdata.io/json-table-schema/#field-constraints

```
 {
  "name": "status",
  "description": "",
  "type": "string",
  "values": ["active", "inactive", "defunct", "temporarily closed"]
}
```

is better expressed as:

```
 {
  "name": "status",
  "description": "",
  "type": "string",
  "constraints": {
    "enum": ["active", "inactive", "defunct", "temporarily closed"]
  }
}
```

**Comment by timgdavies** [comment]
Thanks @danfowler for flagging this. 

@robredpath If I don't get to it before you are working on docs generation next week, please update the sample data first so that you are working on the latest frictionless data specs.

**Comment by robredpath** [comment]
@timgdavies @danfowler 2512e77

**Comment by NeilMcKechnie** [comment]
This is great news, interoperability will be greatly improved if we constrain fields either to a finite list like this or at least a data type. As such, can we consider adding such "type" constraints to other fields like email addresses and ensure other obvious fields like boolean and date/datetime get these constraints too?

**Comment by robredpath** [comment]
Further constraints would be great for interoperability and we're likely to be recommending them for a future version of HSDS. Thanks @NeilMcKechnie !

**Comment by robredpath** [comment]
@NeilMcKechnie Issue #99 may be of interest to you as well.
