### ISSUE TITLE
"float" type should be "number"

### ISSUE THREAD

**Issue by danfowler** [openreferral/specification#101]
```
{
    "name": "latitude",
    "description": "",
    "type": "float"
},
{
    "name": "longitude",
    "description": "",
    "type": "float"
}
```

should be:

```
{
    "name": "latitude",
    "description": "",
    "type": "number"
},
{
    "name": "longitude",
    "description": "",
    "type": "number"
}
```

See: http://specs.frictionlessdata.io/json-table-schema/#number

**Comment by robredpath** [comment]
Thanks @danfowler . Along with #100 (and any other issues you find!), I'll update the documented version of the spec that we're working with in https://github.com/openreferral/specification/blob/updated-documentation/datapackage.json to take account of this, if @timgdavies doesn't get to it

**Comment by robredpath** [comment]
@danfowler 	f58afda
