### ISSUE TITLE
Make "license" field object rather than array

### ISSUE THREAD

**Issue by danfowler** [openreferral/specification#102]
On https://github.com/openreferral/specification/blob/master/datapackage.json#L4

Currently, `license` is defined to as a string or object, not an array:

> `license` is an object OR string. The value of the string version SHOULD be an Open Definition license ID (preferably one that is Open Definition approved. 

> http://specs.frictionlessdata.io/data-packages/#strongly-recommended-fields

Note: options for adding additional licenses to be defined: https://github.com/frictionlessdata/specs/issues/236

**Comment by robredpath** [comment]
@danfowler 3cfaf4c

That branch should get merged in within a few days, so I'm working on all these tweaks on it for now to avoid merge hell later

**Comment by NeilMcKechnie** [comment]
There's another item here suggesting the License, along with a few other items, be collapsed to be just fields in their parent object and I support doing so.

**Comment by robredpath** [comment]
Thanks @NeilMcKechnie . At the moment we're trying to make the smallest possible changes to the schema that will bring it back into line with the Frictionless Data spec and allow us to auto-generate docs from the schema. 

I'll make sure that this issue stays open for that recommendation to be considered for the next actual upgrade, as it's worth discussing.

**Comment by timgdavies** [comment]
I think there were two things being discussed here:

* The copyright license of the contents of a data package
* The license table from HSDS which is discussed in #78 

As this issue was about the former, and I think we were keeping it open for the later (and the later is covered in #78) I'm closing this.
