### ISSUE TITLE
Use current "format" for type "date" fields

### ISSUE THREAD

**Issue by danfowler** [openreferral/specification#103]
On https://github.com/openreferral/specification/blob/master/datapackage.json#L55

Currently, the date format should be specified like "fmt:%Y":

> **fmt:PATTERN**: date/time values in this field conform to `PATTERN` where `[PATTERN]` follows the syntax of [standard Python / C strptime][strptime]. (That is, values in the this field should be parseable by Python / C standard `strptime` using `PATTERN`). Example: `fmt:%d %b %y` would correspond to dates like: `30 Nov 14`

> http://specs.frictionlessdata.io/json-table-schema/#date

Note: see discussion on removing `fmt:` prefix: https://github.com/frictionlessdata/specs/issues/260

**Comment by timgdavies** [comment]
Thanks @danfowler 

I've updated the [instance of date](https://github.com/openreferral/specification/blob/1.0-beta/datapackage.json#L88) on the 1.0-beta branch to reflect this, and have also checked for date and datetime fields.

**Comment by klambacher** [comment]
For clarity, year incorporated is the only case using a pattern, and the rest are using a default of ISO-8601 yes?
