### ISSUE TITLE
physical_address needs concept of a "county"

### ISSUE THREAD

**Issue by NeilMcKechnie** [openreferral/specification#104]
This is important if you want to query the data for entities that physically reside in a specified County. In Canada the notion of a County does exist but it differs from the US in that a) it is not always called a County (Region, Municipality, etc) and b) provinces are not always 100% covered by these entities. I'm sure there are also variations to consider for the UK and other countries too.

**Comment by greggish** [comment]
Is this really needed to address the physical location, or is "county" more relevant to 'service area'?

**Comment by NeilMcKechnie** [comment]
Sometimes you want to search for services "located in" a particular place. Other times you want to search for services that serve a particular place even though they may be located elsewhere. This is very common in our client base to switch between these two modes and as such each needs a well-structured and complete expression of geography.

So they are two different concepts really and hence deserve different treatments in the standard.

**Comment by timgdavies** [comment]
We currently have the following address fields:

* address_1
* address_2
* address_3
* address_4
* city	
* state_province	
* postal_code
* country	

In the UK context, we often put 'county' into the 'state_province' field (e.g 'Gloucestershire' would be my province). Although someone in Scotland or Wales might have that placed between state_province and country. 

There is a lot of other variation in this around the world.

Schema.org uses: 

* addressCountry
* addressLocality
* addressRegion	
* postOfficeBoxNumber	
* postalCode
* streetAddress

With 'locality' and 'region' as the key bits there for handling different levels of administrative geography. 

I think we have quite a few possible options here:

* Recommend use of address_4 for county level information  (no change to structures, just to guidance)
* Add 'county' between 'city' and 'state_province' in the current list
* Switch entirely to a schema.org model
* Encourage consuming applications to do their own geocoding from postcode etc. to get geographic hierarchies

Thoughts and comments?

**Comment by NeilMcKechnie** [comment]
Thanks @timgdavies . Colloquially, the notion of a "county" is essential in the US; in Canada it is important for the most populated areas (although they go by various names there: County, District, Region, Municipality to name a few). I'm a citizen of both countries. People generally well know which county they live in, and services are often offered at a county level. I  think counties are much closer in physical and population size to "shires" on your island than they are to states, just for reference ;-)

Perhaps calling it a Region is the most flexible option.

**Comment by timgdavies** [comment]
I've explored updating the current ```address_1``` ... ```address_4``` fields with definitions that would allow a backwards compatible approach here. However, the inclusion of 'city' as an explicit property makes that difficult. 

As a result, I would propose for 1.1 that we:

* Deprecate ```address_2``` ... ```address_4``` (i.e. recommend these are not used, and plan for their removal in 2.0) 
* Add ```region``` below ```city```

The suggested format for an address would then be:

* ```address_1``` - a street address
* ```city``` - The city or town
* ```region``` - a county, district, region or municipality
* ```postal_code``` 
* ```country```

In 2.0 we could tidy up the nomenclature if required to fully align with schema.org addresses.

**Comment by timgdavies** [comment]
On today's Open Referral Assembly call I think there was general support for removing multiple address_x fields, but there was a request to separate out the 'Care Of' component of addresses.

I also mentioned improving parsers for address information. There is a discussion of that [over here](https://github.com/openownership/data-standard/issues/18) which cites [libpostal](https://github.com/openvenues/libpostal) for address parsing.

**Comment by pmackay** [comment]
While I appreciate the simplification of `address_x` lines, is there a proposal of how addresses like 

Flat A
10 High Street

would be handled?

**Comment by timgdavies** [comment]
This would go into ```address_1``` (which we should consider equivalent of schema.org ```streetAddress``` as a comma or line separated string).

Consuming applications that want to display addresses nicely will need to perform their own parsing.

**Comment by NeilMcKechnie** [comment]
I lean towards retaining Address_2. It is pretty common to have and need this.

**Comment by rasmus-storjohann-PG** [comment]
I would want to avoid building in any country specific assumptions about address formats into the standard, as it will cause friction in adopting it internationally. Having a single text field that can contain newline characters is one way to support various formats. It would then be up to clients to enforce any kind of standardization for a given region, which I think could be OK.
