### ISSUE TITLE
Documentation: regular_schedule should specify location_id?

### ISSUE THREAD

**Issue by NeilMcKechnie** [openreferral/specification#105]
I think this is just a typo  as holiday_schedule has it correct.

https://github.com/openreferral/specification/blob/master/Human%20Services%20Data%20Specification%20%20v1.0.md#vocabulary

**Comment by timgdavies** [comment]
This is fixed in the [datapackage.json version of the spec](http://docs.openreferral.org/en/latest/reference/#regular_schedule).
