### ISSUE TITLE
Consider moving funding to the organization level

### ISSUE THREAD

**Issue by NeilMcKechnie** [openreferral/specification#107]
Practically speaking, most information and referral entities only track this at the organizational level anyways.

**Comment by greggish** [comment]
As I recall, this was related to the conversation about Programs. Governments (and some funders) consider 'program' to mean funding stream. I believe our 'program' represents a bundle of services. So Funding at this level may be important to be able to identify the provenance of a particular resource...

**Comment by NeilMcKechnie** [comment]
OK, not terribly important but I thought I'd mention it.

**Comment by timgdavies** [comment]
Flagging for review in 1.1 discussions

**Comment by timgdavies** [comment]
Reviewed and found funding can currently refer to a service or an organisation (or both), so leaving as is with some minor tweaks to the text descriptions.
