### ISSUE TITLE
Should Latitude/Longitude move from Location to PhysicalAddress?

### ISSUE THREAD

**Issue by NeilMcKechnie** [openreferral/specification#119]
It would seem more natural for coordinates to live with the physical address.

**Comment by timgdavies** [comment]
I think both feel fairly natural - so on the principle of least change, I'd suggest we keep it where it is. 

Unless there is other strong reason for a move?

**Comment by NeilMcKechnie** [comment]
Fine to leave it where it is. But physical_address probably didn't need to be a separate table from location, in retrospect, but I agree let's just let sleeping dogs sleep.
