### ISSUE TITLE
Fields allowing HTML should be HTML Encoded (documentation update)

### ISSUE THREAD

**Issue by NeilMcKechnie** [openreferral/specification#120]
This should be explicitly noted in the documentation, for example the Description field in Organization, Location and Service.

**Comment by timgdavies** [comment]
Flagging for discussion.

@robredpath @ekoner Do you know what behaviour Ohana expects? Does it accept HTML in description fields?

Anyone else got expectations on this? Can we simply document that it is expected that fields might contain HTML?

**Comment by klambacher** [comment]
Neil, are you meaning you want all HTML entities encoded? Strictly speaking, a JSON encode shouldn't require escaping of HTML entities, but if some systems are encoding entities and others aren't expecting it, this will absolutely cause a problem.

Most platforms default to _not_ encoding HTML entities when performing a JSON encode, so I would strongly lean towards not requiring this. I would support an optional flag for this in the metadata table, but if so, it should be applied to all fields and tables and not just a selection of them.

**Comment by klambacher** [comment]
Sorry one more note - are we asking due to security concerns? Because that's maybe a different kind of discussion...a valid one to have, but different :)

**Comment by NeilMcKechnie** [comment]
Kate you're right that JSON probably doesn't need HTML to be encoded. We're probably OK just leaving it un-encoded. When consuming data one could always decode these fields in case someone has encoded them. If it is not encoded, trying to decode shouldn't be a problem.
