### ISSUE TITLE
Adding description to service.csv and location.csv

### ISSUE THREAD

**Issue by timgdavies** [openreferral/specification#122]
Comparing the [Ohana API](http://codeforamerica.github.io/ohana-api-docs/#get-all-services-belonging-to-a-location) and [datapackage.json](http://docs.openreferral.org/en/latest/reference/#service) for services, I noticed that the datapackage.json is missing a ```description``` field.

It looks like this is an omission from the datapackage.json file. 

I'm adding the service description field into 1.0 fixes.

**Comment by timgdavies** [comment]
It appears this issue also applies to location.csv

**Comment by NeilMcKechnie** [comment]
organization, location and service should all have the description field, thanks tim.
