### ISSUE TITLE
Audience field

### ISSUE THREAD

**Issue by timgdavies** [openreferral/specification#123]
The [Ohana API has an 'audience' field for services](http://codeforamerica.github.io/ohana-api-docs/#get-all-services-belonging-to-a-location). Issue #5 discussed renaming this to 'target groups', but it appears the field was never included in the datapackage.json or [common vocabulary](http://docs.openreferral.org/en/latest/vocabulary/) for HSDS. 

Is there any use case for this field? Should it exist in version 1.1.

My current presumption is that it should not be included in 1.1, and will be treated as an ohana-specific extension of HSDS.

**Comment by monfresh** [comment]
I believe the `audience` field originally came from the San Mateo County data we were working with when we first developed Ohana API. I don't think the information in that field is critical. From looking at a few random entries in on http://www.smc-connect.org/, it seems like its contents are already present in the service description and/or the eligibility fields.

**Comment by NeilMcKechnie** [comment]
We don't really support the notion of "audience" either, except via similar concepts like target groups in taxonomy assignments; eligibility requirements, etc.

**Comment by timgdavies** [comment]
Based on this feedback we don't propose any changes in 1.1.
