### ISSUE TITLE
Multiple ways of linking services and locations

### ISSUE THREAD

**Issue by timgdavies** [openreferral/specification#124]
The services object contains a ```location_id``` field for making a one-to-one relationship between a service and the location where it takes place.

The ```services_at_location```  object contains:

* ```id```
* ```service_id```
* ```location_id```
* ```url```	- If the service at this location has a specific URL, that can be provided here.
* ```email``` - If the service at this location has a specific email address, that can be provided here.	

This appears to create two ways to relate a service and location.

In relation to #121 it also seems, with the URL and email fields to introduce an additional way of providing location-specific contact information, which may be better handled by making sure all relevant tables include both ```service_id``` and ```location_id``` foreign keys.

**Comment by timgdavies** [comment]
Adding this to be explored as part of 1.1

**Comment by NeilMcKechnie** [comment]
Good catch. I think that for consistency we should remove the location_id from the services object and only link them via services_at_location.

There are a great many additional fields that might benefit from being put into the services_at_location object, reflecting location-specific variances of service offerings. If we are willing to entertain adding more fields, I could get data from our client base proposing which of those fields are most often used. I don't recall how email and url were decided upon but those are probably not very frequently representative of these variations. I would guess phone numbers, contacts, languages and hours of operation are most common.

**Comment by klambacher** [comment]
In agreement with you Neil - and having definitions about variances help system designers manage the Service@Location variation data *and* help the data managers distinguish when something varies enough that it should be considered a distinct service.
