### ISSUE TITLE
Review mapping between HSDS and UK Service Director schema

### ISSUE THREAD

**Issue by timgdavies** [openreferral/specification#129]
@pmackay has just pointed out the work on the Local Gov Association in the UK developing a Service Description Schema at http://validator.opendata.esd.org.uk/servicedirectoryschema

This covers a similar domain to HSDS and we should look at potential alignments and mappings.

**Comment by pmackay** [comment]
@timgdavies do you know of any common conventions or approaches for describing mappings like this? Or is it typically just simple tables/spreadsheets?

#86 is also similar.

**Comment by timgdavies** [comment]
Clearing milestone so we can take this forward beyond 1.1 - particularly as needs from the UK context arise. 

We took a quick look during the upgrade - but didn't pick up key changes to make at this point.

For a mapping - I've always just gone to simple spreadsheets.

**Comment by robredpath** [comment]
We're actively working on this and related issues at the moment with Porism - closing as there's lots of issues with the detail in.
