### ISSUE TITLE
Code generators for datapackage.json?

### ISSUE THREAD

**Issue by NeilMcKLogic** [openreferral/specification#130]
Not an issue but rather a 'help wanted' : Is anyone aware of code generators for datapackage.json files? I am thinking of something that you feed it the datapackage.json file, and it spits out a class library for you to work with in OOP.

Here's an example going from JSON to C#: http://json2csharp.com/

Yes, one could populate JSON with test data and use the tool above. But I'm thinking of something stronger that enforces the required/optional and data type tags and ranges, relationships and foreign keys, for example.

I asked on frictionlessdata.io but no one is aware of one there.

**Comment by greggish** [comment]
cc @danfowler

**Comment by danfowler** [comment]
I'm not aware of one.

**Comment by mrshll1001** [comment]
I'm closing this as out of scope for issues on the specification repo, I think it's an important discussion but probably one more suited to a thread over at https://forum.openreferral.org/ :-)
