### ISSUE TITLE
Service_at_location - why the url and email fields?

### ISSUE THREAD

**Issue by NeilMcKechnie** [openreferral/specification#131]
I very much support this object type, but wonder how/why it got the fields 'url' and 'email' that it has. Practically speaking I think there would be very few instances where one needs to track those fields at the s@l object.

Relatedly, other there other fields that we think should be available at this level, but without opening a can of worms where people denormalize everything down to this level (instead of properly living at the 'service' and 'location' level) ?

**Comment by klambacher** [comment]
:) I was very perplexed by these when I first saw the format! It would make sense if it represented variations of service delivery at a site, but these are probably lowest down on the list of fields that I would pick for that!

**Comment by timgdavies** [comment]
These were removed in 1.1.
