### ISSUE TITLE
For all email and url fields, ensure the type is not a string but "email" and "url"

### ISSUE THREAD

**Issue by NeilMcKechnie** [openreferral/specification#133]
Most of the occurrences of "email" are specified to be of type "email" rather than "string" but this is not the case in the service_at_location. Here as well as throughout the spec it should be typed as "email".

Similarly, can we have the url fields not typed as "string" but as "url" (if that is a type option) ? These url fields are usually fed into fields in destination systems that turn into clickable hyperlinks, so it is important that they be strongly typed.

Otherwise (and we've seen this many times) you'll get string values like "Visit their website" and "www.abc.com or www.xyz.com" both of which are strings and not strongly typed url's.

**Comment by timgdavies** [comment]
Agreed with this proposal. In https://github.com/openreferral/specification/commit/f969c5aa543e4a642132770a7fe9d6fbd5322609 I've staged this change.
