### ISSUE TITLE
Primary and foreign key column references are supposed to be arrays?

### ISSUE THREAD

**Issue by dsantuc** [openreferral/specification#138]
I notice all the primary and foreign key column references in `datapackage.json` schema objects (`primaryKey`, `foreignKeys[n].fields`, `foreignKeys[n].reference.fields`) are specified as strings, but according to [this version](http://specs.frictionlessdata.io/table-schema/#properties-optional) of the Table Schema spec, they're supposed to be arrays.

(Note that the foreign key examples there show string column references, but according to the [schema](http://specs.frictionlessdata.io/schemas/table-schema.json), they're supposed to be arrays.)

**Comment by timgdavies** [comment]
I'll look at getting this aligned in our 1.1 release. 

Before doing that it would be good to confirm that:

* Data package validators support this change (as I think this is a change to the data package spec from when we last looked...)
* Whether this has any implications for other datapackage tooling;
* Whether it impacts any existing publishers of data;

**Comment by dsantuc** [comment]
For what it's worth, I'm using this library: 

https://github.com/frictionlessdata/datapackage-js

and it happily parses the descriptor with either arrays or strings, in both "base" and "tabular" profiles.

(I was also able to throw in a bunch of random fields not part of the spec and still have it validate, but the "fiscal" profile doesn't validate, so apparently it *is* doing something!)

I think the problem is that these specs seem to be kind of new, so they're changing a lot. Ideally there would be some way of declaring the versions of the various specs (Tabular Data, Table Schema) you're using. (I'm kind of new to this, so I'm not sure if there is or not.)

**Comment by timgdavies** [comment]
Thanks @dsantuc 

I'm going to stick with strings in the 1.1 release of OR, but flag this for future iterations of development - particularly as we review whether 'JSON Table Schema' is our best option for the 'single source of truth' of the schema in future as @kinlane also works on API specifications.
