### ISSUE TITLE
Using CSV on the Web metadata?

### ISSUE THREAD

**Issue by greggish** [openreferral/specification#139]
I recently connected with @danbri, who suggested that we look into [the CSV-on-the-Web](https://www.w3.org/2013/05/lcsv-charter.html) metadata vocabulary.

This may be less relevant for the API-related use cases that we've recently been discussing. But seems like it could address some of the concerns people have had about CSVs as a format.

**Comment by JimSaiya** [comment]
That charter page looks like a good collection of and jumping-off point for all kinds of research on CSV.  Dan(bri) the Man comes through again.  :)

**Comment by mrshll1001** [comment]
I'm closing this as no longer relevant, since as of 3.0 HSDS is a JSON standard. If anyone feels differently, please re-open the issue :-)
