### ISSUE TITLE
Data validators

### ISSUE THREAD

**Issue by NeilMcKechnie** [openreferral/specification#142]
Hi, I think we've discussed this verbally but are there plans to build a "data validator" ? Something that one could feed a package of data (or eventually an API endpoint) and have it assess the compliance to the specification, issuing errors, warnings and suggestions accordingly? 

Something like this would be of great benefit to advancing interoperability.

**Comment by kinlane** [comment]
I have a JSON Schema validator I am working on for it....my JSON schema chops are rusty, so it is taking me a bit to do. I'm doing this and working with your schema dump currently -- my current workload. Will publish URL here when ready.  

Which programming language is your preferred at your shop? I can see if I can have version in.

**Comment by NeilMcKechnie** [comment]
Thanks Kin, C# please.

**Comment by dsantuc** [comment]
Have you looked at Frictionless Data? 

https://github.com/frictionlessdata

They have libraries in a variety of languages for working with datapackages, which do validation. (I've used the PHP one.)

They don't have a C# implementation, but they do have one in Java:

https://github.com/frictionlessdata/datapackage-java

Maybe you can import or adapt that one?

**Comment by greggish** [comment]
Yes, in fact HSDS [uses the Frictionless Data package spec for bundling the CSVs with a JSON file](http://docs.openreferral.org/en/latest/producing_sharing/?highlight=datapackage#producing-and-sharing-compliant-data). This is a helpful suggestion, we could see whether their validator tool could be applicable here.

Also, please note that @spilio developed [an Open Referral 'playground' tool](https://github.com/spilio/openreferral-playground) that could serve some of this purpose. 

Would welcome suggestions for folks on details about what kind of tooling would be useful.

**Comment by greggish** [comment]
Thanks to @spilio, we have a new version of a data validator: https://github.com/spilio/openreferral-validator

Once a few folks have a chance to test and share any feedback, I think we should bring this into the Open Referral repo. 

Thanks, Chris!!

**Comment by robredpath** [comment]
This has now been moved into the OR GitHub Org
