### ISSUE TITLE
Nested JSON representation of HSDS data

### ISSUE THREAD

**Issue by timgdavies** [openreferral/specification#152]
An issue has come up in [discussions over the API specification](https://apievangelist.com/2017/07/17/making-all-sub-resources-available-within-the-core-set-of-human-service-apis/) over whether HSDS should describe a 'sanctioned' way of representing services, organizations and locations as nested objects, containing the information that is, otherwise in the datapackage model, stored in related tables.

For example, a service and phone number is currently represented in HSDS as:

```services.csv```

| id | organization_id | location_id | name | 
|---|----------------|------------|-------|
| c89eb05c |1899600a | 86f30ca893d3 | Never Homeless Helpline | 

and 

```phones.csv```

| id | service_id | number |
|---|-----------|---------|
| 25870bcf | c89eb05c | +1 123 456 789 |

Which a strict API response trying to match HSDS 1-for-1 might provide as:

```/services/```
```json
[{
    "id":"c89eb05c",
    "organization_id":"1899600a",
    "location_id":"86f30ca893d3",
    "name":"Never Homeless Helpline"
}]
```

and

```/services/c89eb05c/phones```

```json
[{
   "id":"25870bcf",
   "service_id":"c89eb05c",
   "number":"+1 123 456 789"
}]
```

However, this could also be displayed by nesting ```phones``` within services to give:

```/services/```

```json
[{
    "id":"c89eb05c",
    "organization_id":"1899600a",
    "location_id":"86f30ca893d3",
    "name":"Never Homeless Helpline",
    "phones":[{
          "id":"25870bcf",
          "number":"+1 123 456 789"
      }]
}]
```

This transformation could be achieved by simple rule-following in most cases. As a draft, this rule might be:

> Where one table has a foreign key pointing to another table, the contents of that table can be nested as an array within a JSON representation of the other table, using the table name as the relevant property name. Any foreign keys remaining in the nested table can be omitted.

It would be good to get views on whether (a) this approach to nesting works; (b) this should be supported as part of an official HSDS 1.2 release to formalise the approach; (c) any other changes to HSDS that might be needed to support this. 

This relies on the idea that the foreign_keys in HSDS 'point upwards'. The one edge case might be services_at_location.

**Comment by mrshll1001** [comment]
Closing this, as 3.0 *is* a JSON-first standard, with the tabular package now a supported serialization :-) The API specification expects JSON and directly references specific schema files as return values.
