### ISSUE TITLE
Bug in service_taxonomy description of id and service_id

### ISSUE THREAD

**Issue by klambacher** [openreferral/specification#154]
I feel there is some confusion about is id vs service_id in service_category; in this case, I would expect "ID" to represent the actual association between the Taxonomy and the Service (in our case, the ID of the "Link") since you've got a field for service_id. But the description of id is "Each service must have a unique identifier" and the description of service_id is "The identifier of the service at the given location". IMO you should have:

1) ID to represent the instance of this category associated with this record (unique in the table)
2) service_id to represent the association of this category to the service
3) service_at_location_id to represent the association of this category to the service delivered at a specific location

Either 2 or 3 would be required, but not both. To my knowledge, categories would not be required to describe locations so location_id is not required, but I certainly wouldn't object to seeing that option. I have also seen a requirement to classify organizations for some use cases, so an organization ID would be a good option as well.

**Comment by timgdavies** [comment]
You are right that there appears to be an error in the current descriptions. 

I think this should be treated as a bug fix as it is clearly incorrect. 

The idea of having the ability to classify a ```service_at_location``` or an ```organization``` I think should be treated as a separate feature request: I'll open a separate ticket for that now. 

### Current definitions

Field Name | Type (Format) | Description | Required? | Unique?
-- | -- | -- | -- | --
id | string | Each service must have a unique identifier. | True | True
service_id | string | The identifier of the service at a given location. | True | False
taxonomy_id | string | The identifier of this classification from the taxonomy table. | True | False

### Suggested bug fix

Field Name | Type (Format) | Description | Required? | Unique?
-- | -- | -- | -- | --
id | string | Each **service_taxonomy entry** should have a unique identifier | True | True
service_id | string | **The identifier of the service to which this taxonomy term applies.** | True | False
taxonomy_id | string | The identifier of this classification from the taxonomy table. | True | False
