### ISSUE TITLE
accessibility_for_disabilities enums

### ISSUE THREAD

**Issue by klambacher** [openreferral/specification#157]
The enums in this field are constraining values in a way that make it challenging for people to follow good guidelines for describing accessibility (https://www.fs.fed.us/eng/toolbox/acc/acc17.htm). Strongly recommend removing these enums, which are not comprehensive or descriptive enough to be useful.

**Comment by timgdavies** [comment]
The current enums are:

* "cd"
* "deaf_interpreter"
* "disabled_parking"
* "elevator"
* "ramp"
* "restroom"
* "tape_braille"
* "tty"
* "wheelchair"
* "wheelchair_van"

@greggish may have insights into the history of this list. 

Are there any views on the proposal to remove the enum, and leave this free-text / user specified?

**Comment by greggish** [comment]
I suspect this was a bunch of examples, not an intentional set. 

@klambacher are you saying there's already a standard set of accessibility issues? 

I think it could make sense to leave free, although I'd like to hear from more stakeholders on the matter.

**Comment by robredpath** [comment]
MINOR - remove the constraint

MAJOR - refactor to taxonomy

**Comment by mrshll1001** [comment]
Closing as I cannot find reference to these enums anywhere in 3.0 via grep or the schema reference docs. I believe that since 3.0 was a MAJOR upgrade, these have been refactored to a taxonomy.
