### ISSUE TITLE
removal of additional address lines

### ISSUE THREAD

**Issue by klambacher** [openreferral/specification#158]
I have a **very strong objection** to the deprecation of additional address lines in postal_address. Canadian Postal Guidelines (https://www.canadapost.ca/tools/pg/manual/PGaddress-e.asp) very clearly include up to 4 lines before the city, and this should be an option available. Merging address lines can result in unreadable addresses or undeliverable mail. Those who cannot manage additional lines should be responsible for merging (and the consequences thereof) on the receiving end.

**Comment by timgdavies** [comment]
This was discussed in #104 and went through into 1.1 based on the review process. 

It would be good to get views from others on this.

**Comment by klambacher** [comment]
I think the issue is the line breaks. Having a free-text, multi-line address in a single field is workable. Having a single-line, giant mush of an address is not. If you indicate that line breaks may be included, people can choose to replace them with commas, split on the line breaks, or parse in some other way. But commas are a terrible delimiter in this case, because they are frequent parts of the text that have nothing to do with line breaks. It is obviously essential that we keep the ability to compliant with local postal guidelines, and current specs make that impossible.

**Comment by timgdavies** [comment]
Discussed on today's call, the big issue here is that in the deprecation notes we say:

> we recommend including all address information before ‘city’ **as a comma separated list** in address_1

This is too strong, as sometimes addresses include meaningful commas that do not denote different address lines.

As a result we should either:

update this to say 

> "we recommend including all address information before ‘city’ as a comma **or newline** separated list in address_1

leaving applications to resolve what they get incoming, or, just leave out any such specification of how things should be concatenated in address_1 all together.

**Comment by timgdavies** [comment]
I've staged an update to amend the deprecation note on 1.1.1
