### ISSUE TITLE
payment_accepted enums; capacity for more detail

### ISSUE THREAD

**Issue by klambacher** [openreferral/specification#159]
Rather than an enum, would prefer these as suggested values in the description of the field. These values are non-comprehensive and also US-centric.

I would also like to see an ability to include notes or details along with the payment type.

**Comment by timgdavies** [comment]
For reference, the current enums are:

* "cash"
* "check"
* "money order"
* "credit card"
* "medicare"
* "SNAP"
* "WIC"
* "EBT"

**Comment by robredpath** [comment]
MINOR - removing the constraint (MINOR for publishers, potentially problematic for data users)

MAJOR - reworking this into a taxonomy

**Comment by mrshll1001** [comment]
Closing as I cannot find a reference to `payment_accepted` or any of the enum values here in 3.0, either on the schema reference page of the docs or via grep. To me this indicates that HSDS has moved away from modelling this field.
