### ISSUE TITLE
language details

### ISSUE THREAD

**Issue by klambacher** [openreferral/specification#160]
I would like to see the capacity to provide additional detail on languages. This is a strong requirement. For example:

French: not available at all times; please call ahead

In addition, many of the programs in our database have additional general notes about service languages. If the detail field was added (per above) it would be helpful to be able to send this additional detail with the language code to indicate general information about language of service not tied to one language.

**Comment by timgdavies** [comment]
This feels like a good case for a `language_details`field? Would that fit your envisaged use cases?

**Comment by klambacher** [comment]
Yes, what I had in mind was language_details that can be an amendment to the specific language...however, I would also like to see the language code (current "language" field in this table) be optional in this scenario so that you can have a general language note not tied to a specific language. This latter case is actually the only way to cope with data from many systems in my experience, where all they have is a single free-text field with language information.

**Comment by mrshll1001** [comment]
I'm closing this as I believe that 3.0's [language schema](http://docs.openreferral.org/en/latest/hsds/schema_reference.html#language) meets this need.
