### ISSUE TITLE
Allow organization and service_at_location to be categorised with taxonomy

### ISSUE THREAD

**Issue by timgdavies** [openreferral/specification#162]
At present service_taxonomy is used to related `service` objects to `taxonomy` objects, classifying a service. 

From #154 via @klambacher:

> To my knowledge, categories would not be required to describe locations so location_id is not required, but I certainly wouldn't object to seeing that option. I have also seen a requirement to classify organizations for some use cases, so an organization ID would be a good option as well.

This suggests either:

* Introducing a parallel 'service_at_location_taxonomy' (or just 'location_taxonomy') table, and 'organization_taxonomy' table; or
* Renaming 'service_taxonomy' to 'taxonomy_link' and including multiple possible identifier columns for `service_id`, `location_id` and `organization_id`

Views on the use-cases and approaches to be taken here would be welcome.

**Comment by NeilMcKechnie** [comment]
@timgdavies , I agree with @klambacher. I prefer your second approach of "taxonomy_link". But since 1.1 is approved I would think this would need to be in a future rev of the spec.

**Comment by boxfoot** [comment]
@klambacher could you share a bit more about the use case for this?  Under what circumstances would a service-at-location need to have different taxonomy codes applied than the underlying service itself?

**Comment by MikeThacker1** [comment]
I've raised this as a more general need for taxonomies for multiple types of entity as [issue 208](https://github.com/openreferral/specification/issues/208).

**Comment by robredpath** [comment]
MINOR - adding lots more tables

MAJOR - adding a more expressive taxonomy mechanism and using it in more places, with better names and terminology

**Comment by mrshll1001** [comment]
Closed. See #208, we can attach taxonomies and attributes to most objects/schemas now :-)
