### ISSUE TITLE
Make deprecations more clearly visible

### ISSUE THREAD

**Issue by pmackay** [openreferral/specification#169]
I was looking at https://openreferral.readthedocs.io/en/latest/reference/#physical_address and just noticed now that the `address_2/3/4` fields are deprecated, but its not particularly obvious.

Could the deprecation be highlighted in bold, or a colour, in a separate paragraph? 

Would it be worth indicating when it will be removed?

**Comment by timgdavies** [comment]
HSDS doesn't have a full deprecations policy yet - but I would anticipate removal in the next MAJOR version update (e.g. 2.0).

I'm adding a temporary jquery/css hack to style the deprecated fields which should be live shortly.
