### ISSUE TITLE
Handling long field names in new HSDA docs 

### ISSUE THREAD

**Issue by Bjwebb** [openreferral/specification#178]
The table on the HSDA search page, http://docs.openreferral.org/en/include-api-docs/hsda/hsda-search/, currently overspills the page.

![image](https://user-images.githubusercontent.com/634/33130669-05cc0db8-cf8c-11e7-8120-7b474d3d7db5.png)

**Comment by Bjwebb** [comment]
An alternative is to make the field names wrap:

![image](https://user-images.githubusercontent.com/634/33130743-3e87a05e-cf8c-11e7-92db-03b0e4ee36ad.png)

This looks a little bit ugly, but I think if we break on slashes, then it's probably the least bad solution. Thoughts @timgdavies @greggish ?

**Comment by greggish** [comment]
I defer to @kinlane . 
Should this issue be in https://github.com/openreferral/api-specification ?

**Comment by kinlane** [comment]
I would leave this in the UI / doc layer.  You wouldn't want spaces injected into spec, but the ui/ doc layer could inject the space safely just for the visual presentation.

**Comment by Bjwebb** [comment]
Agreed that this is just for visual presentation, I can modify the sphinx directive that generates the table to do this. The directive lives in this repo, hence the issue is here also.

**Comment by timgdavies** [comment]
@bjwebb I think the suggested modification is the best option for now. 

The alternative would be to have two rows for each entry, with the first row with a colspan like we do in OCDS docs. If that's not a lot trickier to implement, then it might be preferable.

**Comment by Bjwebb** [comment]
Here's what two rows looks like:
![image](https://user-images.githubusercontent.com/634/34106747-49d564f4-e3f1-11e7-8676-7a7b6be6d1f8.png)

I personally don't like it as much (just in terms of the look, no technical reason), but it's easier to implement, so happy to go with it if you prefer.

**Comment by Bjwebb** [comment]
Here's what's easy to do:
![image](https://user-images.githubusercontent.com/634/34110773-902b75d4-e3ff-11e7-81f0-41f5360d74f9.png)

**Comment by greggish** [comment]
Seems like that's an improvement in readability. I'm fine with it, but i'm not the target user. We could ask for folks to weigh in via slack?

**Comment by Bjwebb** [comment]
Yes, that could be useful. I don't think I'm on the slack.

**Comment by timgdavies** [comment]
@greggish If you get feedback views on this issue from Slack that would be great. We can implement updated version first thing in the New Year if there is agreement that the look above is preferred (I quite like it)

**Comment by greggish** [comment]
No comment in slack. If it works for @kinlane, it wfm

**Comment by kinlane** [comment]
Thumbs up!

**Comment by Bjwebb** [comment]
I have a branch and a PR where I've enabled the new layout for all HSDA tables:
Preview: http://docs.openreferral.org/en/178-long-fieldnames/hsda/hsda-search/
Pull request: https://github.com/openreferral/specification/pull/186
