### ISSUE TITLE
Better indicate required <> optional distinction, and bring back 'recommended' status

### ISSUE THREAD

**Issue by greggish** [openreferral/specification#189]
I'm hearing feedback that people want to better understand which fields are required vs optional in various contexts. This might not be one fix, so much as a set of steps to provide clearer context. 

Also, HSDS 1.0 sorted non-required fields into 'recommended' and 'optional' categories, while v1.1 did away with that distinction. We should consider bringing back the 'recommended' designation to indicate common high-value but non-required fields.

**Comment by robredpath** [comment]
An alternative solution here might be "profiles" - either customised versions of the standard or just super-explicit guidance on which fields are useful in which contexts.

**Comment by mrshll1001** [comment]
Closing since we've addressed this in 3.0. We have clearly marked Required fields on the schema reference page, and we also have a robust Profiles mechanism which serves marking other fields as required for other contexts.
