### ISSUE TITLE
Question: ER Diagram `SERVICE_AT_LOCATION` table's Primary key

### ISSUE THREAD

**Issue by adityasrini** [openreferral/specification#190]
Hello maintainers, I have a question about your [ER diagram](https://openreferral.readthedocs.io/en/latest/_images/hsds_er_diagram_v1.1.png). In your table titled `SERVICE_AT_LOCATION`, you have a primary key titled `ID`. @chewgley and I were trying to figure out whether or not the primary key was unique or if it was a composite key comprising of the `service_id`, and `location-id` fields. If it is a unique value for each entry, I want to know what purpose that would serve that wouldn't be served by a combination of the two fields.

**Comment by NeilMcKechnie** [comment]
Hi @adityasrini , I am not the official keeper of the spec, but my opinion is that if the service_at_location entity matches something in your own schema, then it would make sense to populate with its unique id. The purpose served is it would cleanly relate back to the source schema for purposes of doing updates, etc. In our case the equivalent entity is quite rich in data fields and functionality so we want to keep the reference to our unique id's intact when emitting HSDS.

If not, I would think a composite of service_id and location_id would make sense. I don't recall if HSDS specifies this id as an int or as a string, but if the latter you might do something like prefix the service_id with an "S" and the location_id with an "L", for clarity when generating the composite.

**Comment by greggish** [comment]
Thanks @NeilMcKechnie ! 

@adityasrini i can add this to the list of things to bring to @timgdavies' attention when he next cycles back here, but at first glance i trust Neil's suggestion. Just make sure to document whatever you choose. And let me know if I can help think this or other issues through in the meantime!

**Comment by timgdavies** [comment]
@adityasrini I'd agree with @NeilMcKechnie here. HSDS is agnostic about how you construct `id` values - and they will vary in their structure from system to system.
