### ISSUE TITLE
Transit Options

### ISSUE THREAD

**Issue by kinlane** [openreferral/specification#192]
Introduce more fields to support public transit options for locations / services.

**Comment by klambacher** [comment]
We've got a few types of transportation fields and they serve different purposes:

- Transportation services provided: does the service / organization provide assistance in securing transportation, or does it provide transportation services directly? Is the client / volunteer required to secure transportation to access services? This may be a selection of some pre-defined common values that can be picked checklist style, but *always* needs the ability for open-text explanation.

- Public transit (often labelled "Bus Routes"): a list of nearby routes. This draws from a list of pre-defined routes that are selected checklist-style. The route information allows capture of the route system, route name, and / or number. Standards should define what is considered close enough to qualify as a nearby route.

**Comment by mrshll1001** [comment]
I am provisionally closing this as I cannot find reference to the term transit in HSDS 3.0, in either the documentation or the schema files. To me this indicates that the spec has moved away from describing transportation.

Please re-open this if modelling transport is still relevant to the spec!
