### ISSUE TITLE
Phone Options

### ISSUE THREAD

**Issue by kinlane** [openreferral/specification#193]
Expand phones “type” to include TTY and other phone types (Toll free, free call).

**Comment by robredpath** [comment]
MINOR for publishers; risk of breaking if data consumers rely on only values in codelist

**Comment by mrshll1001** [comment]
I am closing this based on 3.0 having in the `phone.type` description:

> Indicates the type of phone service, drawing from the RFC6350 list of types (text (for SMS), voice, fax, cell, video, pager, textphone).

I think this is addressed. There is no enumeration or codelist applied, so all strings are validated but the semantics are that the code should be drawn from the stated list.
