### ISSUE TITLE
Semantics of "required"

### ISSUE THREAD

**Issue by aidan-fitz** [openreferral/specification#202]
I see that the section on [producing and sharing compliant data][producing] says that "A null value is acceptable for required fields." While reading through the reference, I was under the impression that "required" meant that every object must have the field, as in `NOT NULL`, but if null values are permitted then this can't be correct. What does "required" mean in this context? We should clarify it in the [reference].

[producing]: https://openreferral.readthedocs.io/en/latest/hsds/producing_sharing/
[reference]: https://openreferral.readthedocs.io/en/latest/hsds/reference/

**Comment by greggish** [comment]
Hi @aidan-fitz, sorry for the holiday-mode delay. 

Thanks for your question. I'm no authority on technical matters, but I was under the impression that when a field is 'required,' that doesn't necessarily mean the field's value is NOT NULL. NULL in a required field is, essentially, an assertion that such data does not exist (which is valuable info :)

Is there some other context you have in mind re required vs null? Depending, it might make sense to add a note of clarification to the reference page.

**Comment by aidan-fitz** [comment]
I was thinking that it might just mean that the field has to be _provided_ in the CSV, not that all values of it have to be filled. Frankly this might have been more clear in the context of the old "required", "recommended", and "optional" ratings.

**Comment by spilio** [comment]
As the Open Referral resource schema is based on the [Table Schema](https://frictionlessdata.io/specs/table-schema/#constraints) specification this statement is definitely not valid.  A required value should be present.  The new validator I am currently working on uses the official libraries from Frictionless Data and their parser will throw an error in this case.  Also according to the spec for fields not required, the column should be present in the CSV and at the correct index to be considered valid even though it has no values.

**Comment by robredpath** [comment]
Closing as this seems to have been answered. Please do re-open if required!
