### ISSUE TITLE
"description" or "definition" field in taxonomy table

### ISSUE THREAD

**Issue by JordanLyons** [openreferral/specification#211]
I feel like including a description or definition of each record in the taxonomy table might be useful and popular enough to merit inclusion in the HSDS. Open to others' thoughts on this. Thanks!

**Comment by MikeThacker1** [comment]
My view is that the taxonomy_id (alone or combined with the "vocabulary") should be sufficient to be able to link to the full taxonomy/vocabulary maintained outside of the Open Referral standard. That is where the description/definition and potentially many other properties may be held for the taxonomy term.

Looking at our data, I see we use the full URI (eg [http://id.esd.org.uk/service/730](http://id.esd.org.uk/service/730) ) for service type. This resolves in a web browser to show information in properties that are defined by [DCTerms](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/) and [SKOS](https://www.w3.org/TR/skos-primer/).

**Comment by devinbalkind** [comment]
I think this is useful to include as well.

Our clients often want to display descriptive text next to categories in their browse views - and rarely are they referencing some third party taxonomy.

**Comment by robredpath** [comment]
This is incorporated in a new proposal about taxonomies - please see https://docs.google.com/document/d/10PAWTrHn6zHuFVUUpsibjD5UmnhmrIkRQDFk7pKA0Pw/edit#heading=h.1j4g3dch4jc9 and let me know if it works!

**Comment by mrshll1001** [comment]
Closing as both taxonomy and taxonomy_term schemas have a desciption fielda s of 3.0
