### ISSUE TITLE
Documentation Does Not List Acceptable Values For Enum Fields

### ISSUE THREAD

**Issue by AtticusRains** [openreferral/specification#212]
The HSDS [objects and fields reference documentation](http://docs.openreferral.org/en/latest/hsds/reference/#objects-and-fields) currently does not list acceptable values for enum fields (or denote that these fields are enums at all) as described in the datapackage.json

For example, the eligibility.eligibility field is described in the datapackage.json as follows:

```
{
    "name": "eligibility",
    "description": "The rules or guidelines that determine who can receive the service.",
    "type": "string",
    "constraints": {
        "enum": ["adult","child","teen","family","female","male",
            "Transgender", "Transgender - M to F", "Transgender - F to M" ]
    }
}
```

The documentation makes this field seem more like an open text field and does not list the acceptable values.

| Field Name | Type (Format) | Description | Required? | Unique?|
| ---------------| ------------------ | ---------------| --------------| -----------|
|eligibility | string | The rules or guidelines that determine who can receive the service. | False | False|

**Comment by MikeThacker1** [comment]
Yes it is currently defined just as a text field. In the UK we're proposing an extension so that eligibility can come from a taxonomy/vocabulary. See [issue 208](https://github.com/openreferral/specification/issues/208).

**Comment by mrshll1001** [comment]
Closing this as we no longer have eligibility modelled in this way. However I'm noting that there's been several other issues discussing how enums in the standard are not rendered properly.

Usually this is handled separately, via a codelists page. I am noting this down in our project docs as being related to this.
