### ISSUE TITLE
tables in repo specification but can't find it in the specification,  docs describe # Version 1.1 but the github page has # Version 1.2; 

### ISSUE THREAD

**Issue by japrogramer** [openreferral/specification#217]
In there is no "categories" table mentioned http://docs.openreferral.org/en/latest/hsds/reference/

but https://github.com/openreferral/specification/blob/master/database/hsda_core.sql
has such a table that isn't referenced by other tables.

There also seems to be a Fee table that is not in the spec .. ill edit this comment if I find others.

Edit: so Far
* categories
* fee
* interpretation_service
* users

**Comment by japrogramer** [comment]
also some tables have id must be unique, some say uuid but others don't .. is it ok to use all as UUID?

**Comment by japrogramer** [comment]
There also seems to be a Fee table that is not in the spec .. ill edit this comment if I find others.

**Comment by japrogramer** [comment]
It seems that the docs describe # Version 1.1 but the github page has # Version 1.2 of HSDS

**Comment by greggish** [comment]
@japrogramer thanks for the sharp eye, and for the issues. 

First off, I fixed the link to the reference implementation, appreciate the heads up.

Next, I think the ID issue has been flagged at #199, in which case it's slated to be patched in the current upgrade cycle by @robredpath. please take a look to confirm. I also assume we'd clean up the versioning confusion that you mention in the current cycle.

Finally, we should look into those inconsistencies w/r/t the tables you mentioned. I think `categories` is misnamed from `taxonomy` but I'm not sure. We do have `fees` and `interpretation_services` in the spec as fields, not tables. `Users` may be specific to HSDA (the API protocols) and not HSDS. We'll have to ask @kinlane for this. 

I appreciate the input and thank you in advance for your patience!

**Comment by kinlane** [comment]
HSDA is all taxonomy - http://docs.openreferral.org/en/latest/hsda/hsda-taxonomy/

**Comment by greggish** [comment]
@kinlane can you clarify the `Categories` table? 

And, it seems like the API specs refer to `fee` and `interpretation_service` as tables, when in the spec they're fields. (I know some implementations have expanded these into tables, but I don't think we'd made that change to HSDS...)

**Comment by kinlane** [comment]
The [hsda_core.sql](https://github.com/openreferral/specification/blob/master/database/hsda_core.sql) referenced above appears to be a MySQL dump from an older specific implementation. The HSDS spec should dictate the data structure, and the HSDA spec should dictate the API access to that schema. We should clean that up to reduce confusion, and add to list of work to maintain specific table dumps for MySQL, PostGres, and SQL Server.

**Comment by MikeThacker1** [comment]
In the UK our SchemaGenerator code (see  https://github.com/OpenReferralUK/human-services/blob/master/SchemaGenerator/README.md ) will generate the SQL from a tabular data package. 

This may also exist elsewhere. We use MySQL. I'm not sure if/how it differs for PostGres and SQL Server

**Comment by kinlane** [comment]
I can generate an update to MySQL package once I get a fresh view of the current version. I will try to make sure it doesn't get lost in the shuffle like the one you came across did.

**Comment by mrshll1001** [comment]
I am closing this because I believe that HSDS has moved on in its modelling and the discussion no longer is directly relevant to 3.0 and beyond. Please reopen if this is a mistake on my part!
