### ISSUE TITLE
Contact id field required to be unique but doc says unique is false

### ISSUE THREAD

**Issue by japrogramer** [openreferral/specification#218]
![image](https://user-images.githubusercontent.com/1387859/82594609-f73c0a80-9b69-11ea-9d73-2912de7fbea3.png)

**Comment by japrogramer** [comment]
![image](https://user-images.githubusercontent.com/1387859/82595825-e55b6700-9b6b-11ea-9161-a9bc3ac9b3c2.png)

Here ids are described as uuids in tables were they aren't explicitly described as uuid,
does this mean that all `id` should uuids?

**Comment by greggish** [comment]
@robredpath is this related to #199 and/or #203?

**Comment by robredpath** [comment]
Hi @japrogramer 

Thanks for this; we're addressing the missing unique constraints in the [2.0 upgrade](https://github.com/openreferral/specification/pull/219) 

The mention of UUIDs there is confusing; I've removed it in the 2.0 draft as well.

**Comment by mrshll1001** [comment]
Closed as this has been fixed.
