### ISSUE TITLE
Columns on HSDS Reference page don't line up

### ISSUE THREAD

**Issue by odscjames** [openreferral/specification#237]
http://docs.openreferral.org/en/latest/hsds/reference/

If you look at the source code, you'll see:

```
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 50%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
```

So we are trying to set up column widths to be standard across all tables on that page. Makes sense, that makes it easier to scan.

However it's not working, in firefox or chrome:

![cols-not-lined-up](https://user-images.githubusercontent.com/37832009/124747350-bb086c80-df19-11eb-97b8-40fa1f52f93f.png)

**Comment by mrshll1001** [comment]
Closing as we've changed how we render these tables in 3.0 due to the move to JSON Schema. They all line up nicely :-)
