### ISSUE TITLE
HSDS / Sample & Detail Dates page links

### ISSUE THREAD

**Issue by odscjames** [openreferral/specification#239]
HSDS has 2 pages:

* Sample http://docs.openreferral.org/en/latest/hsds/sample_data/
* In Detail: Opening Dates & Times in HSDS http://docs.openreferral.org/en/latest/hsds/detail_dates/

However, these pages do not appear in the left hand menu or the list of pages on http://docs.openreferral.org/en/latest/hsds/

I think they should do - if you look at the list at the bottom of https://github.com/openreferral/specification/blob/bb01361405633d4e8234e21552d983290d550660/docs/hsds/index.md you'll see both sample_data  & detail_dates in there.

Q: Should those 2 pages have links in the left menu and the list of pages on http://docs.openreferral.org/en/latest/hsds/
 ?

**Comment by greggish** [comment]
Just to clarify, you're saying that these are 2 pages that exist in the documentation but are not included in the menu items – is that right?

I do think it could be worth including the Sample Data page in the menu and list, even though it links back to the repo. It's an often-requested resource.

As for the 2nd one (Open Dates & Times) now that i see that, I wonder what the difference is between that and 
http://docs.openreferral.org/en/latest/hsds/schedules/ ?

**Comment by odscjames** [comment]
> Just to clarify, you're saying that these are 2 pages that exist in the documentation but are not included in the menu items – is that right?

Yes.

**Comment by greggish** [comment]
OK so yes the sample data should be included in the menu. 

I wonder if the Open Dates & Times should be a child of Schedules http://docs.openreferral.org/en/latest/hsds/schedules/?

**Comment by mrshll1001** [comment]
Closing as this is no longer applicable to version 3.0
