### ISSUE TITLE
HSDS Use cases & HSDA index - leads to a deleted Google doc

### ISSUE THREAD

**Issue by odscjames** [openreferral/specification#242]
Link in 

* "Read more about each of these personas in our User Personas documentation."
* "(as documented in user personas and use cases generated through our community’s participatory research process)."

**Comment by greggish** [comment]
The current version of this doc is [here](https://docs.google.com/document/d/1aodu4BUDVbUwVD02zlFs0WkCMn3UQEX1VHyI8ej6BCU/edit).
