### ISSUE TITLE
HSDA Index page - broken link

### ISSUE THREAD

**Issue by odscjames** [openreferral/specification#243]
"Find the core HSDA protocol in a YAML file here."

**Comment by greggish** [comment]
Let's file in [/api-specification/issues](https://github.com/openreferral/api-specification/issues)

**Comment by odscjames** [comment]
Done commit. This changes from GitHub to the files included in the docs. 

This is important because it means that if the docs use older versions of the API Standard or someone is looking at an older version of the docs, they will also see the old version of HSDA used at the time. With the GitHub link, they always saw the newest.

**Comment by mrshll1001** [comment]
Closing as HSDS 3.0 replaces this with the API Specification page, which includes links to the openapi.json file and a swagger UI representation.
