### ISSUE TITLE
HSDA Overview - History section has broken link

### ISSUE THREAD

**Issue by odscjames** [openreferral/specification#245]
"HSDA v1.1 is accessible for reference."

**Comment by odscjames** [comment]
The only thing I can find to link to is https://openreferral.github.io/api-specification/v1.1/openapi.yaml - the actual YAML file.

I'll change that as it's still better than a 404, but I don't know if we should be finding an old version of the docs to link to? I'll leave this issue open to discuss that.

**Comment by odscjames** [comment]
Also, should we be linking to V1.0 and V1.2 as well?

**Comment by mrshll1001** [comment]
Closing as we have replaced History with a [Changelog](http://docs.openreferral.org/en/latest/hsds/changelog.html)
