### ISSUE TITLE
HSDS Index - Spacing in list of pages

### ISSUE THREAD

**Issue by odscjames** [openreferral/specification#246]
This is after https://github.com/openreferral/specification/pull/238 is merged

Above any nested list of secondary pages, there is a extra space.

It seems to be because of this new CSS rule that wasn't there before:

```
.rst-content .section ol li > *, .rst-content .section ul li > * {
    margin-top: 12px;
    margin-bottom: 12px;
}
```

**Comment by mrshll1001** [comment]
Closing as I believe this no longer applies, given the new theme since 3.0 (which seems to be working).
