### ISSUE TITLE
Example data - link to in docs, and clear up language

### ISSUE THREAD

**Issue by odscjames** [openreferral/specification#256]
* There is the page http://docs.openreferral.org/en/latest/hsds/sample_data/ but it's not in the menu and the content will need updating.
* Samples & examples is used inconsistently; standardise on example.

Broken out from https://github.com/openreferral/specification/pull/255

**Comment by mrshll1001** [comment]
Closing as the sample_data page is no longer part of the docs. We can open up a new ticket if we want to add a new/updated version of this in.
