### ISSUE TITLE
Update Example Data

### ISSUE THREAD

**Issue by odscjames** [openreferral/specification#257]
Broken out from #255

See comments:

@robredpath 

> The actual content of the sample data - especially around things like where the original creator chose to use UUIDs where they're not technically required, and the confusion that might lead to.

@greggish 

> As for the non-required UUIDs... hard to say. Are they not only nonrequired, but also not useful? If they're not required but having them there could be useful for some purposes, then I don't think they need to come out. If it's an instance in which IDs were added to entities that really don't need IDs, then it might make sense to take them out.
>
>I guess this brings up a different issue, which is: would it be worth assembling a minimally-viable data example, and also a 'complete' data example??

**Comment by mrshll1001** [comment]
Closing this issue as addressed since the docs review updated all of the examples including ensuring that uuids were in appropriate places
