### ISSUE TITLE
datapackage.json - other_attribute - link_type 

### ISSUE THREAD

**Issue by odscjames** [openreferral/specification#270]
The description is the same as the description on link_id and seems incorrect.

**Comment by Cskyleryoung** [comment]
Just noticed this as well. Raised the point with some folks in our Slack workspace. Perhaps we can get this updated in the next release.

**Comment by mrshll1001** [comment]
Closing, as there does not appear to be a property called `other_attribute.link_type` in the current datapackage.json file as of 3.0. Please re-open if this is incorrect.
