### ISSUE TITLE
Taxonomy and term identifier, label and URI

### ISSUE THREAD

**Issue by MikeThacker1** [openreferral/specification#272]
Sorry I didn't pick this up earlier, but [taxonomy_term](http://docs.openreferral.org/en/latest/hsds/reference/#taxonomy_term) in HSDS 2.0 does not make provision for separate identifiers, labels and URIs for taxonomies or taxonomy terms.

As I understand it, "id" is an identifier within the "dataset" of services, not within the taxonomy.

As an example in the UK we might reference:

- services taxonomy URI: http://id.esd.org.uk/list/services
- services taxonomy label: "All services"
- services taxonomy identifier: "services"
- service taxonomy term URI: http://id.esd.org.uk/service/242
- services taxonomy term identifier: 242
- services taxonomy term label: "Care at home"

The reference page says for taxonomy "If possible, provide a URI". I'm wondering about the case for combining label and URI in one field - hence requiring someone to go to the URI (if one is given) to get the taxonomy label.

**Comment by devinbalkind** [comment]
I've been confused about taxonomy_terms in HSDS 2.0 as well. 

I was hoping to use that table for both service categories as well as service eligibility. Maybe even organization taxonomies too. But it doesn't seem that's supported. 

I also think that there is value in having a table for taxonomies that can define various taxonomies (ex. open eligibility, AIRS, system) and link them to taxonomy terms, which might accommodate the user case Mike is describing here.

**Comment by MikeThacker1** [comment]
I think the "link_type" field in [other_attribute](http://docs.openreferral.org/en/latest/hsds/reference/#other_attribute) can be made "organization" to associate taxonomy terms with organizations.

The [Classifications page other_attributes example](http://docs.openreferral.org/en/latest/hsds/classifications/#other-attributes) illustrates the approach with a link_type of "program".

There is a question as to how we represent eligibility, in service_attribute referencing a taxonomy term that clearly defines a type of eligibility OR in other_attribute with an appropriate link_type.

**Comment by mrshll1001** [comment]
Closing as I believe this has been addressed in 3.0, please check the [taxonomy_term](http://docs.openreferral.org/en/latest/hsds/schema_reference.html#taxonomy-term) model and reopen the issue if you think more work is needed.
