### ISSUE TITLE
datapackage.json - schedule - service_id / location_id notes

### ISSUE THREAD

**Issue by odscjames** [openreferral/specification#279]
This is currently optional - should it be required?

http://docs.openreferral.org/en/latest/hsds/reference/#schedule

(location_id is not required but that makes sense because a service may be virtual , by phone, etc)

**Comment by odscjames** [comment]
Actually, I'm guessing from the schedule description the intention is that a schedule can be attached to a location, which might run many services.

But in that case it seems sensible to:
* attach a note to schedule saying "One of service_id or location_id MUST be set". Rows without either don't make sense. We should log this as a check the validator would have to do itself as I don't think we can define this in our schema.
* attach a note to schedule saying "When looking up a schedule for a service, you should check the schedule data for service_id=X but also look in service_at_location for a list of location_id's then check the schedule data for location_id IN X,Y,Z"

**Comment by mrshll1001** [comment]
Closing as HSDS 3.0 has updated to a JSON model, where schedules are embedded under various other objects.
