### ISSUE TITLE
Indicate license in the Readme and documentation site

### ISSUE THREAD

**Issue by greggish** [openreferral/specification#287]
I just realized it's not easy to see what the license is on our docs site or in the README. I suppose there's some complexity in that there are different assets with different licenses (usually varying according to software vs conceptual products), though [the primary license is CC BY-SA 4.0](https://github.com/openreferral/specification/blob/master/LICENSE) and we [aim to keep other licenses consistent with that](https://docs.google.com/document/d/1W81WtFVgnIIz_ko8PVtvoQrnb-_AbwlKTDPGvPo6dIk/edit).

**Comment by dan-odsc** [comment]
Closing #495
