### ISSUE TITLE
schedule.count and schedule.wkst

### ISSUE THREAD

**Issue by benjamin-wunder** [openreferral/specification#291]
The schedule schema has some issues with data types.

Count should be a number, not a date

Wkst should be a string, not a date

I created a pull request to fix this in the specs b/c I wasn't sure what the procedure was.

It's here: https://github.com/openreferral/specification/pull/289

**Comment by Cskyleryoung** [comment]
Just noticed these same issues when defining the schema for one of our apps. @devinbalkind  can we add this to 2.1, or is it already in there?

**Comment by MikeThacker1** [comment]
I've noted in cells W155 and W156 of [Por20349 - HSDS - US and UK](https://docs.google.com/spreadsheets/d/1Ew5aKgVAwEcFVR9H7FG-Z6ybJkeY4U8VM_IHN3u1cG4/edit?usp=sharing) that the data types need to be corrected. 
We should probably separate documentation correction from release version numbers.

**Comment by mrshll1001** [comment]
These were fixed in 3.0 :-)
