### ISSUE TITLE
Write swagger spec

### ISSUE THREAD

**Issue by lgs85** [openreferral/specification#301]
Holding issue for writing the swagger spec for the HSDS 3.0 upgrade. May be broken down into multiple issues.

**Comment by mrshll1001** [comment]
Update for clarity: OpenAPI (swagger) specification written at `openapi.json`. There may be some edits and errors that emerge as part of incorporating into the docs site, so keeping this open for now.

**Comment by lgs85** [comment]
Thanks @mrshll1001 happy to take a look at the build issues if helpful

**Comment by lgs85** [comment]
This is now implemented. Closing.
