### ISSUE TITLE
Write API documentation

### ISSUE THREAD

**Issue by lgs85** [openreferral/specification#303]
Once the API upgrade is completed in #300 #301, we will need to write a set of non-normative documentation to accompany the specification upgrade. This is a holding issue to post ideas around what this might look like.

**Comment by dan-odsc** [comment]
https://github.com/openreferral/specification/issues/301#issuecomment-1452021522

**Comment by dan-odsc** [comment]
@mrshll1001 moved this to in-progress.

**Comment by dan-odsc** [comment]
Please ignore the above comments. Can't find a way to delete them.
