### ISSUE TITLE
Final review of reference and guidance documentation

### ISSUE THREAD

**Issue by lgs85** [openreferral/specification#305]
Once the initial edits to guidance and reference documentation have been made, we'll need to do a full review of the structure and content of the docs pages.

**Comment by lgs85** [comment]
The link to the schema files in the schema reference page will need updating, as this points to the 3.0-dev branch. We also need to check for other links to 3.0-dev.

**Comment by mrshll1001** [comment]
Closing as related to pre-3.0 release.
