### ISSUE TITLE
Update and document tooling

### ISSUE THREAD

**Issue by lgs85** [openreferral/specification#307]
For the HSDS 3.0 upgrade we will need to update and document changes to all relevant tooling. This is a holding issue for this work.

**Comment by lgs85** [comment]
[Profile generator](https://schema.openreferraluk.org/)

**Comment by dan-odsc** [comment]
Planio Ticket for this work - https://opendataservices.plan.io/issues/37202

**Comment by dan-odsc** [comment]
Please ignore my last comment. I've conflated this with the work we're doing on tooling requirements.

I assume these 3 still need to be updated?

- [Profile generator](https://schema.openreferraluk.org/)
- [Schema generator](https://github.com/OpenReferralUK/human-services/tree/master/SchemaGenerator)
- ERD generator
