### ISSUE TITLE
Change json-schema directive?

### ISSUE THREAD

**Issue by lgs85** [openreferral/specification#338]
The layout of the tables on the [reference page](http://docs.openreferral.org/en/3.0-dev/hsds/reference.html) of the docs is not ideal, with two rows per field. We should consider whether we want to adopt a [different existing directive](https://sphinxcontrib-opendataservices.readthedocs.io/en/latest/jsonschema/#) or to create a new custom directive. Thoughts welcome.

**Comment by mrshll1001** [comment]
Closing as I believe we're doing this now.
