### ISSUE TITLE
Update FAQs (3.0)

### ISSUE THREAD

**Issue by lgs85** [openreferral/specification#341]
We will need to update the FAQs page to be consistent with the 3.0 upgrade. For example, the [section about the format of HSDS](http://docs.openreferral.org/en/3.0-dev/faq.html#what-is-the-format-of-the-hsds-why-csv) is out of date.

**Comment by greggish** [comment]
This is on my list of things to do. I think we might end up consolidating the FAQ on the website with this FAQ, and restructuring it so that different sets of Qs can be presented in different contexts. Would welcome your input into what we should update and any other questions we should add to answer.

**Comment by lgs85** [comment]
Thanks @greggish that's good to know. I'll have a full read of the website and docs FAQs and come back with some thoughts.

**Comment by lgs85** [comment]
@greggish from a 3.0 perspective, I think that the only questions that need updating are the ones on [format](http://docs.openreferral.org/en/latest/faq/#what-is-the-format-of-the-hsds-why-csv), and on [taxonomies](http://docs.openreferral.org/en/latest/faq/#how-do-you-address-the-matter-of-taxonomy-of-types-of-services-and-situations). The latter is just some broken links I think. The format question is on both the website and the docs, and will need to reflect the change in format of the schema.

I don't see an urgent need for additional technical FAQs at this stage - hopefully we can make the reference clear enough in of itself. It might be useful, though, to think about a high level question about the approach to the API spec, and how this interacts with HSDS. 

I'm happy to help with editing the format question, and/or to help with adding, removing and editing initiative-level questions from the docs site if that's part of your intended work. Let us know what works best for you. @dan-odsc

**Comment by dan-odsc** [comment]
@mrshll1001 - Updates to FAQ's are as follows:  

- Current FAQ -[What is in the Human Services Data Specification (HSDS)?](http://docs.openreferral.org/en/3.0-dev/faq.html#what-is-in-the-human-services-data-specification-hsds) 
Updated content - https://docs.google.com/document/d/1VfoH8a5GL0ZKCNMzm1Y_oiezvDxsHkhLB9MeWGjuNlI/edit#heading=h.ssupkv1035jr


- Current FAQ - [What is the format of the HSDS? Why CSV?](http://docs.openreferral.org/en/3.0-dev/faq.html#what-is-the-format-of-the-hsds-why-csv)#
- Updated content - https://docs.google.com/document/d/1VfoH8a5GL0ZKCNMzm1Y_oiezvDxsHkhLB9MeWGjuNlI/edit#heading=h.tk4rlak47km5

- Current FAQ -[How do you address the matter of taxonomy (of types of services and situations)?](http://docs.openreferral.org/en/3.0-dev/faq.html#how-do-you-address-the-matter-of-taxonomy-of-types-of-services-and-situations)
- Updated content - https://docs.google.com/document/d/1VfoH8a5GL0ZKCNMzm1Y_oiezvDxsHkhLB9MeWGjuNlI/edit#heading=h.feeo0evroq7u

- Current FAQ - [What if I need help collecting this data in the first place?](http://docs.openreferral.org/en/3.0-dev/faq.html#what-if-i-need-help-collecting-this-data-in-the-first-place)
- Updated content - https://docs.google.com/document/d/1VfoH8a5GL0ZKCNMzm1Y_oiezvDxsHkhLB9MeWGjuNlI/edit#heading=h.q9i3ttrwdfg

- Current FAQ - [Who do I contact if I need help with this project?](http://docs.openreferral.org/en/3.0-dev/faq.html#who-do-i-contact-if-i-need-help-with-this-project)
- Updated content - https://docs.google.com/document/d/1VfoH8a5GL0ZKCNMzm1Y_oiezvDxsHkhLB9MeWGjuNlI/edit#heading=h.u1qvt6iemyrw

- Current FAQ - [What languages is this project in?](http://docs.openreferral.org/en/3.0-dev/faq.html#what-languages-is-this-project-in)
- Updated content - https://docs.google.com/document/d/1VfoH8a5GL0ZKCNMzm1Y_oiezvDxsHkhLB9MeWGjuNlI/edit#heading=h.5s7pa5pqb0ms


- Current FAQ - [If I wanted to help with this project, what is the best way to do that?](http://docs.openreferral.org/en/3.0-dev/faq.html#if-i-wanted-to-help-with-this-project-what-is-the-best-way-to-do-that)
- Updated content - https://docs.google.com/document/d/1VfoH8a5GL0ZKCNMzm1Y_oiezvDxsHkhLB9MeWGjuNlI/edit#heading=h.1ysrzelhcfcl

Current FAQ - [Is the project in active development?](http://docs.openreferral.org/en/3.0-dev/faq.html#is-the-project-in-active-development) 
- Updated content - https://docs.google.com/document/d/1VfoH8a5GL0ZKCNMzm1Y_oiezvDxsHkhLB9MeWGjuNlI/edit#heading=h.dvd4ecnwkacv
