### ISSUE TITLE
Update `test_examples` workflow

### ISSUE THREAD

**Issue by lgs85** [openreferral/specification#355]
The `test_examples.yml` [workflow](https://github.com/openreferral/specification/blob/3.0-dev/.github/workflows/test_examples.yml) currently builds a datapackage and tests examples from there. We should consider testing the examples directly from the JSON schema files.

**Comment by Bjwebb** [comment]
All the new examples are validated now, and we're removing the old ones https://github.com/openreferral/specification/pull/412
