### ISSUE TITLE
Populate example tabs for API Reference page

### ISSUE THREAD

**Issue by mrshll1001** [openreferral/specification#378]
[This commit](https://github.com/openreferral/specification/commit/b6fdb9115d42db7df31454bcd65137ea5fc5038e) adds tabs to the API reference page. There are two tabs for each endpoint:

* Details -- containing the openapi-sphinxcontrib generated endpoint details
* Example -- designed to point towards some JSON schema examples of the returned data.

At present, all Examples are pointed towards a single JSON schema file. These need to be change.

Also, consider whether "Details" and "Example" are the best names for these tabs. Very happy to accept/review changes on these.

**Comment by lgs85** [comment]
Closed by #379
