### ISSUE TITLE
Actions to prepare for 3.0

### ISSUE THREAD

**Issue by mrshll1001** [openreferral/specification#396]
* Updating the Get In Touch section with link to the forum (https://forum.openreferral.org/c/technical/7)
* Add UK specific changes to a subsection of the UK compliance section and link from the main change log ([reference](https://docs.google.com/document/d/1sdaxXNsw3EcB7Oz6cjn_jaG16bMM1-d3Gj3jyOZTkzI/edit#heading=h.ezorg8ngoxw3))
* Clarify definition of uri as a identifier rather than a location ([see this section](https://docs.openreferral.org/en/3.0-dev/hsds/api_reference.html#response-details))

**Comment by dan-odsc** [comment]
- Review updates to 3.0 related q's. Once confirmed update Github and WordPress accordingly [https://docs.google.com/document/d/1VfoH8a5GL0ZKCNMzm1Y_oiezvDxsHkhLB9MeWGjuNlI/edit#heading=h.k8nkc5bi916y](url)

- Review 360 feedback and agree actions.

**Comment by dan-odsc** [comment]
- Update Open API links to ensure they got to 'latest' version when we go live.

**Comment by dan-odsc** [comment]
- We are missing the Accessibility section in Schema Reference: [Schema Reference — Open Referral Data Specifications 3.0.1 documentation](https://docs.openreferral.org/en/3.0-dev/hsds/schema_reference.html#accessibility)

**Comment by dan-odsc** [comment]
Thanks for all your work on this Matt!
