### ISSUE TITLE
Agree on an approach to feeding FAQ's into Wordpress/Docs

### ISSUE THREAD

**Issue by dan-odsc** [openreferral/specification#397]
Not to be confused with 

What has been discussed so far?

- Using the FAQ section on the Docs as a SSOT and link to there from the Wordpress site.
- Creating separate lines for each FAQ on a spreadsheet for each question. Pull form there to wordpress/docs accordingly. 
- Stick with Markdowns in a google doc and just transfer content to docs/wordpress

Categories:

- General/Overview 
- Product/Technical
- Project/Strategic/Governance 

- Initiative/About Open Referral
- Standard/About HSDS

**Comment by dan-odsc** [comment]
Greg has been looking to this - https://wordpress.org/plugins/ultimate-faqs/

**Comment by greggish** [comment]
I have no idea if that's good, just wondering whether there are FAQ tools
for wordpress that might also work with whatever tactic we use to manage
these for the documentation etc.

**Comment by dan-odsc** [comment]
@mrshll1001 @kindly 

Update on this:

We are still working on updating content, consolidating questions and agreeing on categories but won't be long until we have a list of FAQ's in [this ](https://docs.google.com/spreadsheets/d/1TRb78P67C4qciJdxwNeWZj05WV41AQDUBT3UDHuC9Cs/edit#gid=399327506)or a similar format.

Once we're at this point we will need technical support get this data surfacing on wordpress and the docs.
