### ISSUE TITLE
Add introductory copy to Swagger Page

### ISSUE THREAD

**Issue by dan-odsc** [openreferral/specification#424]
Context here - https://forum.openreferral.org/t/3-0-for-review-and-comment/364/12?u=dan-ods

SwaggerUI - https://docs.openreferral.org/en/latest/openapi.html

**Copy** 

Open Referral develops data standards and open source tools that make it easier to share, find and use information about health, human, and social services i.e. community resource directory data. Our Human Service Data Specification (HSDS, AKA ‘the Open Referral format’) is a data exchange format that enables resource directory data to be shared among heterogeneous information systems. 

We provide an [OpenAPI](https://www.openapis.org/) specification that can be used as a blueprint for the design or adaptation of API platforms to provide read or read/write access to information on organizations, services, locations and the details about them. The API protocol provides most of the functionality needed for simple access and exchange of data.

This Swagger UI will aid the development of API's that will validate against the Open API specification. 

For further info please see:
- [API Reference Section in the Docs](http://docs.openreferral.org/en/latest/hsds/api_reference.html#)
- [API Specification (GitHub)](https://github.com/openreferral/specification/tree/3.0/schema/openapi.json) &  [Issue tracker](https://github.com/openreferral/specification/issues)

**Comment by dan-odsc** [comment]
Context here - https://forum.openreferral.org/t/3-0-for-review-and-comment/364/12?u=dan-ods 

SwaggerUI - https://docs.openreferral.org/en/latest/openapi.html

**Comment by kindly** [comment]
Updated this here
http://docs.openreferral.org/en/3.0/openapi.html

**Comment by dan-odsc** [comment]
Thanks David! Will let Devin know and close this issue. Dan

**Comment by dan-odsc** [comment]
Devin updated on forum
