### ISSUE TITLE
Review then archive HSDS Github Repo

### ISSUE THREAD

**Issue by dan-odsc** [openreferral/specification#450]
Form Greg - My understanding is that we no longer consider HSDA to be a separate product. Should we also archive [its Github repo](https://github.com/openreferral/api-specification/issues)? There may be some important content still in open threads there, but one way or another this feels like a loop we should close…

Rob - Yeah, we should archive that repo. I've not checked the "open threads" that Greg is referring to but a quick review and maybe a summary of points in issues in main OR standard repo would probably suffice.

**Comment by dan-odsc** [comment]
Matt's review of open issues:
https://docs.google.com/document/d/1z1YFjaqytItNaoXLZ64kSQKfmhk1v78KVBhJUIFxG2o/edit

Next steps TBA

**Comment by mrshll1001** [comment]
I have closed the issues that have been addressed elsewhere as part of HSDS 3.0, we've noted the other issues and will sort/group/manage them appropriately, and I've now archived the repo on github with a message to users at the top of the README explaining why.

**Comment by dan-odsc** [comment]
Have began the process of creating issues in the Specification Repo (labeled API Spec Repo Issues) for those marked as API-specific 

https://docs.google.com/document/d/1z1YFjaqytItNaoXLZ64kSQKfmhk1v78KVBhJUIFxG2o/edit

**Comment by dan-odsc** [comment]
The repo has been archived. All issues reviewed and either; Linked to an issue on the specification repo, Not linked because not relevant or closed.

Documented here - https://docs.google.com/document/d/1z1YFjaqytItNaoXLZ64kSQKfmhk1v78KVBhJUIFxG2o/edit#heading=h.m4kj343teo9z

Further review/priorisation can now take place using via the repo.
