### ISSUE TITLE
3.1 upgrade summaries

### ISSUE THREAD

**Issue by dan-odsc** [openreferral/specification#499]
There was a request (agreed on by all) that a short summary of each of the 19 issues we’ve proposed (see[ ‘Proposed’ column](https://github.com/orgs/openreferral/projects/2)) would help them to understand what we’re proposing and allow them to engage more effectively at this early stage. This would be an intermediary step that would proceed a formal proposal.

**Comment by dan-odsc** [comment]
Draft Summary Doc - https://docs.google.com/document/d/1mXeBN6bme9Y9zND5O_7yGW5tnwqKc9ALoQOM1Q8QBC8/edit

**Comment by kathryn-ods** [comment]
This was done - you can see the individual proposals here https://forum.openreferral.org/t/approving-3-1-proposals/561/4
