### ISSUE TITLE
Allow virtual (phone/web) locations

### ISSUE THREAD

**Issue by debsherwin** [openreferral/specification#69]
The way I'm reading the spec, it looks like both physical and mail address are required for every location. And every service requires a location, thus, no web-based or phone-based locations (ie. virtual locations) are allowed.

However, a service like a crisis hotline may have no location, or at least no physical location.
http://sfhomeless.wikia.com/wiki/California_Youth_Crisis_Line

Additional wrinkle:
There may be a location, but it is not meant to be public. This occurs in
http://sfgov2.org/ftp/_gfx/reentry/documents/Getting-Out-Staying-Out.pdf

Would "call for location" belong in the notes? or should it be a special location type?

**Comment by monfresh** [comment]
Hi @debsherwin. These are both great suggestions. Thanks!

I thought that we had already added support for virtual locations, but looks like we didn't yet. In Ohana API, we allow virtual locations by setting a Location's `virtual` attribute to `true`, as explained in our [Wiki](https://github.com/codeforamerica/ohana-api/wiki/Populating-the-Postgres-database-from-OpenReferral-compliant-CSV-files#locationscsv-required).

As for locations that are not meant to be public, that could also be easily solved by adding an attribute to the Address entity called `private`, and set it to `true`. That way, an app such as [Ohana Web Search](http://ohana-web-search-demo.herokuapp.com/) would know not to show the address if it sees that it is private. Instructions such as "call for address" would best belong in the Location description.

These both seem like easy additions to the spec. What do you think @spara?

**Comment by ajpik** [comment]
There are organizations with secret locations (the ones I know of are all domestic violence shelters) that they will not share with us even if we promise not to show the location on our internet-facing tools. We handled this in our original design by requiring [a street address] OR [[checking that the organization has no location] AND [the broader region served by the organization]].

An example of the service region is "Massachusetts" or "Boston." This allows geographically-based searches to "find" the organization without its specific street address when the search is within that area (or near its geographic center).

**Comment by spara** [comment]
Move issue to post 1.0

**Comment by timgdavies** [comment]
(Working on reviewing issues ready for next round of spec bug fixes and revisions)

The formal HSDS [spec allows for virtual locations](http://docs.openreferral.org/en/latest/reference/#location). 

Ohana API has some stricter requirements, as noted above.
