### ISSUE TITLE
language-specific phone numbers

### ISSUE THREAD

**Issue by debsherwin** [openreferral/specification#70]
Is it appropriate to put the name of a language in the "number_type" field of a phone number?

As in, call X number for someone to answer in English, but call Y number for someone to answer in Spanish. 

This is not for Interpretation services, just to know which number to call for a location.

**Comment by spara** [comment]
No, number type describes whether it is a fax, sms, voice, hot line, etc.

**Comment by greggish** [comment]
In the case of services that offer different phone contacts for different languages, what would be an appropriate designation?

**Comment by ckoppelman** [comment]
If I were modelling that, I would put language as another column on Phone Number.  How often is this the case?

**Comment by fureigh** [comment]
Some services have designated [TTY](https://en.wikipedia.org/wiki/Telecommunications_device_for_the_deaf) lines for [ADA compliance](http://nad.org/issues/civil-rights/ADA), which I'd think would fall under language as well. Don't know how often it's the case, but it's an important circumstance to account for.

**Comment by ckoppelman** [comment]
TTY, in my mind, is a `number_type`, like fax or voice.  Language, on the other hand, is the medium of the content, not the method of transportation of content.

**Comment by fureigh** [comment]
@ckoppelman That makes sense. Thanks!

**Comment by timgdavies** [comment]
I think there are two potential proposals here, both of which would be well suited to a 1.1 release:

### (1) Clarifying the use of the ```phone.type``` field. 

At present, this is defined as:

> Whether the phone number relates to a fixed or cellular phone.

However, this doesn't capture the textphone case. This could be clarified by drawing on section [6.4.1 of the vCard spec](https://tools.ietf.org/html/rfc6350#section-6.4.1 ), which sets out a codelist of types for phone services which should be widely supported

![image](https://cloud.githubusercontent.com/assets/342624/21154243/926d2eae-c165-11e6-8e8b-a8996b53a2dd.png)

I would propose making type a constrained list of values, drawn from this codelist. 

This would allow services to locate the relevant phone number for a textphone user, or to identify services that support SMS.

The one further issue to resolve here though is whether the field should allow a comma separated array of types (e.g. for a phone service that supports both sms and voice), or whether the recommended action in these cases should be to duplicate a row in the ```phone``` table, one for each kind of phone service provided. 

### (2) Language

For this, the clear proposal appears to be to add a field to indicate which languages a phone service can handle. 

For this, following [schema.org](https://schema.org/ContactPoint)'s ```availableLanguage``` field name would seem most appropriate - potentially as ```available_language``` to fit the current idiom of Open Referral.

Decisions to make for this will be:

* Whether to require BCP47 language tags (e.g. 'en', 'es') or to allow free-text languages (E.g. 'English', 'Spanish', 'Español') 
* Whether to allow a comma separated list of languages in the field, or require field duplication again

**Comment by timgdavies** [comment]
Noting that an alternative to allowing language on phone fields is to clearly document how the [language table](http://docs.openreferral.org/en/latest/reference/#language) should interact with contact details to represent the languages available via a particular contact point.

**Comment by ckoppelman** [comment]
I agree with the `phone.type` proposals and the `phone.available_language` proposal.  My recommendation (consistently) is that any language field uses ISO-639-2/-3 (e.g., eng, spa, deu) since unlike ISO-639-1, ISO-639-2/-3 includes languages more often spoken by vulnerable populations (like many Native American languages).

My reluctance to adopt the full flexibility of BCP47 is that most users don't care if the phone is answered in `ar-u-nu-latn` (that is, Arabic with Latin numerals), or `yue-hant-ZH` (Cantonese as spoken in China using traditional characters).  All they care about is `ara` (Arabic) or `yue` (Cantonese).  Making it BCP47-compliant is a burden on parsers, validators, and search algorithms, and can create database-level validation accidents (assuming simple two-letter codes, or three-letter codes).

I do not believe the language table can adequately capture a phone line's available languages.

**Comment by NeilMcKechnie** [comment]
Chiming in my support of @timgdavies proposal to separate Type and Language, and that Type needs to be multi-selectable. 

I like having a hard coded list of type choices but I think the vCard list is a little weird . Does anyone use a pager anymore? Does it matter if it is a "cell" phone, as long as we know it supports both voice and text? And "textphone" sounds too much like it is for texting. Is there some other better/more modern standard we could use?

**Comment by NeilMcKechnie** [comment]
Also, what happened to my earlier suggestion to support fields in the Phone object for Name and Description? Was it incorporated in 1.0? If not shall I add it for 1.1 ?

**Comment by ckoppelman** [comment]
Might this whole process be going too hard on phone, specifically?  Aren't there many communications channels that a helpseeker can use to access services?  What about IM, Twitter, Skype, or "over-the-top" messaging like SnapChat, Signal, etc?
