### ISSUE TITLE
Requirements discrepancy between tabular data and controlled vocabulary

### ISSUE THREAD

**Issue by monfresh** [openreferral/specification#75]
In the [Controlled Vocabulary](https://github.com/codeforamerica/OpenReferral/blob/master/Human%20Services%20Data%20Specification%20%20v1.0.md#a-controlled-vocabulary-for-human-services-data) section, many of the entities that are listed as `recommended` or `optional` are listed as `required` in the [Tabular Data](https://github.com/codeforamerica/OpenReferral/blob/master/Human%20Services%20Data%20Specification%20%20v1.0.md#tabular-data-package) section.

Are the requirements not meant to be consistent in those two sections?

Also, the tabular data section says "A CSV file is required for each entity in the logical model," but then it lists some as optional or recommended. That is confusing.

**Comment by timgdavies** [comment]
In the 1.0-beta branch I'm working through aligning the datapackage.json (from which documentation tables are now generated), and the Controlled Vocabulary section.

My understanding is that some of the required fields under Controlled Vocabulary are driven by requirements from Ohana, and are not necessarily things that should be required by HSDS long-run.

However, to be able to consult on this, I'm starting by following the requirement from the Controlled Vocab section to get us to consistent documentation, and we can then propose dropping out some of the required elements from the next release of the spec.
