### ISSUE TITLE
Consider making CSV file names pluralized

### ISSUE THREAD

**Issue by monfresh** [openreferral/specification#76]
Since each CSV file is meant to contain multiple rows, the file names should be pluralized to better represent their contents.

**Comment by monfresh** [comment]
Since this spec is inspired by GTFS, why not adopt their best practice of using singular versus plural file names based on what they represent? https://developers.google.com/transit/gtfs/reference#FileRequirements

**Comment by pmackay** [comment]
+1 for plural. 

Also would be great to resolve so that pages like https://github.com/codeforamerica/ohana-api/wiki/Populating-the-Postgres-database-from-the-Human-Services-Data-Specification-%28HSDS%29-compliant-CSV-files can be more aligned with HSDS, so either HSDS does use plural names or Ohana is updated to parse singular names.

**Comment by timgdavies** [comment]
In theory, in a data package, the filenames are not strictly defined.

Instead, consuming applications should read the datapackage.json file, look for the [resources it contains](http://frictionlessdata.io/guides/data-package/), and then pick up the filename from the path parameter in the datapackage. We have learnt this week also that the latest version of the datapackage spec will allow files to be an array (e.g. such that the data for services could be split across multiple CSVs)

However, in practice, we know that people will want to follow a naming convention - and that Ohana also assumes particular (plural) filenames.

I don't see a substantial reason not to update the filenames to plural as part of the 1.0 tidy up.

@greggish Would you be happy with this as a bug-fix to the current schema? 

I'm not aware of any existing bulk collections of HSDS files, apart perhaps from our sample data and Miami pilot, which would be affected by this.

**Comment by greggish** [comment]
Fine by me, but I'd like to hear from other implementers (or would-be implementers) whether this makes sense to them.

**Comment by timgdavies** [comment]
Done in 1.0 release
