### ISSUE TITLE
Consider renaming payments_accepted to accepted_payments

### ISSUE THREAD

**Issue by monfresh** [openreferral/specification#77]
`payments_accepted` sounds like it could be a boolean field that denotes whether or not payments are accepted, whereas that ambiguity does not exist when the field is named `accepted_payments`. Moreover, it would be more consistent with the naming of the `required_documents` field.

**Comment by timgdavies** [comment]
The proposed change is also consistent with Schema.org format of [acceptedPaymentMethod](https://schema.org/acceptedPaymentMethod) and would make sense. 

However, currently tagging this against 2.0 as it would be a breaking change for anyone currently publishing or expecting payments_accepted field.
