### ISSUE TITLE
Update Interpretation Services to a free text field for description of services available

### ISSUE THREAD

**Issue by monfresh** [openreferral/specification#79]
The description implies that the field is meant to be a collection of language codes, which is not what we decided back in December. This field is meant to provide a description of the various types of interpretation services available at a location. This is meant to be a rich text field that would contain one or more sentences, such as "We offer 3-way interpretation calls via a third party called XYZ (with a link to the XYZ website). We also have a native Spanish-speaker on premises on Wednesdays".

**Comment by timgdavies** [comment]
I've updated the proposal in #78 to reflect this.

**Comment by timgdavies** [comment]
This will be handled in the updates on 78.
