### ISSUE TITLE
Modelling multiple associations

### ISSUE THREAD

**Issue by pmackay** [openreferral/specification#81]
As an example, if there is a person who is a contact for multiple organisations, how would that be defined in an OR dataset? Would the `id` field be the same on two rows representing the same person, with only the `organisation_id` or `service_id` being different? Or if the `id` has to be different for each row, is the contact info duplicated?

**Comment by NeilMcKechnie** [comment]
My view is that the person should have a unique entry for each organization they belong to. This logic would apply for any object type: contact, physical_address, location, service, etc. It is just so much cleaner if they always belong to exactly one organization. Yes it does mean some duplicated data but only at the expense of keeping the overall structure clean and predictable.

**Comment by timgdavies** [comment]
I believe @NeilMcKechnie describes the current behaviour that systems would expect.

I suggest we make this explicit in the tidied up version of 1.0 documentation.

**Comment by klambacher** [comment]
I agree w/ each contact having its own entity with each Organization. An update to contact information with one Organization does not imply changes with other Organizations, and tying them together can lead to unintentional data errors. Sometimes they are the same literal person, but have different positions or contact methods depending on the Organization and their role in it, etc.

**Comment by timgdavies** [comment]
I've tweaked documentation in 1.0 - and will carry forward this issue in #121 for further updates.
