### ISSUE TITLE
Was a "type" attribute considered for Organisation or Location?

### ISSUE THREAD

**Issue by pmackay** [openreferral/specification#83]
This is just a question, but in some of the work I've been doing recently we're trying to model these things and its quite useful to have a `type` field (or perhaps category) that describes what kind of thing it is. 

So a Location might have a list of types such as:
- school
- shop
- church
- etc

An organisation might have:
- corporation or business
- non-profit
- etc

Any info on this much appreciated.

**Comment by monfresh** [comment]
For the location type, you might want to check out what we did for [San Mateo County](https://github.com/smcgov/SMC-Connect). We called the field "Kind", and you can search for one or more kinds on [smc-connect.org](http://www.smc-connect.org/).

As for the organization type, perhaps the existing `legal_status` field would suit your needs.

**Comment by timgdavies** [comment]
@pmackay I know this is from a while ago - but would welcome any input from you on whether you would still propose a ```type``` field for organisations.

I think we would need to get a good few documented use-cases to consider including this in the spec, as it is not something that many systems are likely to have internally in any particularly standard way. 

However, there is nothing to stop individual implementations extending the HSDS with a property like this.

**Comment by klambacher** [comment]
The values you have for organization are in line with the "legal status" field in the AIRS standard and the former "Service Level" field used by data standards bodies in Ontario/Canada previously. I would agree this is useful at the organization level (legal status is often a required field by various data standards).

What you are describing above as Service Types would for example fall under the "Organization/Facility Type" Terms in the AIRS Taxonomy. What do you see as the use case for this information? I think the closest I have seen is in mapping systems that use special icons for certain facility types, but even when we implemented this ability in our system it really wasn't used.

**Comment by pmackay** [comment]
`type` for a Location might be the kind of thing an asset mapping list for a local community could create. But I appreciate it may rarely be captured in datasets relevant to OR.

`legal_status` certainly covers one kind of categorisation for Orgs, which is useful.
