### ISSUE TITLE
Relationship between programs and departments?

### ISSUE THREAD

**Issue by keithporcaro** [openreferral/specification#84]
It seems a little strange that departments only exist as a field in a model, rather than a model itself. I might think of an organization as having n departments with m programs and x services, and a department might be an individual contact point within an organization. What's the envisioned relationship between organizations, departments, and programs?

**Comment by NeilMcKechnie** [comment]
As soon as you open this door, arguments can be made for an infinitely recursive hierarchy and there is some merit to doing so. For example hospital networks and federal government agencies can have quite a deep organizational hierarchy. But on a practical basis it becomes quite burdensome to work with data that potentially has such deep hierarchy, Our clients tend to address this by just giving the organization a name that reflects the most meaningful components of that hierarchy. for example: "Kaiser Permanente - Northern California - Radiology" and then it might have named services like "X-ray" and "Diagnostic Practitioners" etc.

**Comment by timgdavies** [comment]
Agreed with @NeilMcKechnie that the complexity created here by capturing organisation hierarchies would be substantial. 

Closing this issue - but happy to re-open and explore more if there are specific use cases raised to support further investigation.
