### ISSUE TITLE
foreignKeys resource references the foreign resource path rather than the resource name 

### ISSUE THREAD

**Issue by philipashlock** [openreferral/specification#89]
Admittedly, I don't have much experience with JSON Table Schema, but I think the implementation of the `foreignKeys` might be slightly out of alignment with the JSON Table Schema spec. Currently the value for `resource` used in `foreignKeys` is the `path` of the foreign resource, but I think it should be the `name` as the [JSON Table Schema spec says](http://dataprotocols.org/json-table-schema/#foreign-keys):

> MUST have a property resource which is the name of the resource within the referenced data package. For self-referencing foreign keys, the value of resource MUST be self

So for example the resource with a `name` of "program" and a `path` of "program.csv" the `foreignKeys` should look like 

``` javascript
                    "foreignKeys": [
                        {
                            "fields": "organization_id",
                            "reference": {
                                "resource": "organization",
                                "fields": "id"
                            }
                        }
                    ]

```

rather than 

``` javascript
                    "foreignKeys": [
                        {
                            "fields": "organization_id",
                            "reference": {
                                "resource": "organization.csv",
                                "fields": "id"
                            }
                        }
                    ]

```

**Comment by danfowler** [comment]
Thanks @philipashlock.  This should be fixed 👍 .

**Comment by robredpath** [comment]
Thanks @danfowler @philipashlock . I'm picking up @timgdavies 's work in improving the schema at the moment - does #fc55529 do what we want?

**Comment by timgdavies** [comment]
I think this has been fixed now.
