### ISSUE TITLE
address, organization, and location relationships

### ISSUE THREAD

**Issue by elplatt** [openreferral/specification#92]
There are no keys linking postal_address/physical_address to organizations. In airtable, I've added an organization_id field to both address tables in order to create example data.

**Comment by NeilMcKechnie** [comment]
Shouldn't those just link to Location objects, which themselves are children of Organizations?

**Comment by timgdavies** [comment]
@NeilMcKechnie is correct on this. In the HSDS model it appears postal and physical addresses always belong to the location of an organisation.

I've sketched out the relevant part of the model below (as part of attempts to capture a simplified version of the overall model... still ongoing...) 

![image](https://cloud.githubusercontent.com/assets/342624/21159871/b273c914-c17a-11e6-8fa3-75ceab97d805.png)
