### ISSUE TITLE
holiday schedule and organization relationship

### ISSUE THREAD

**Issue by MaxWhitney** [openreferral/specification#93]
There is no key linking holiday_schedule to organizations. In airtable, I've added an organization_id field to holiday_schedule table in order to create example data.

**Comment by monfresh** [comment]
`holiday_schedule` is an attribute of a Location, not an Organization. There is no direct relationship between an Organization and a schedule. An Organization could potentially operate at many different Locations, each with its own Holiday Schedule.

**Comment by monfresh** [comment]
I updated my previous comment to add Services. A Schedule can be tied to either a Location or a Service (or both), but not to an Organization.

**Comment by NeilMcKechnie** [comment]
I agree with Monfresh - these should not be children of Organization as they relate to service delivery.

**Comment by timgdavies** [comment]
This was based on a reading of the database diagram from the logical model, which appears to include more relationships that are present or intended in HSDS.
