### ISSUE TITLE
Switch to Github-only for spec documentation.

### ISSUE THREAD

**Issue by greggish** [openreferral/specification#96]
Accessibility of the spec documentation was an early issue for us, and we originally chose to use both Google Docs and Github simultaneously. Moving forward, I agree that we should have a single source of the spec. For various reasons, Github is preferable to Google Docs. 

But we need a solution that can be a) shared in an immediately visual format, and b) easy for people to comment on without having to go through the steps of learning Github and issues. (This may not be a lot of steps, and we can certainly provide training, but we don't want to put up a barriers in front of most of the people who we want to read the spec, who will be unfamiliar with this system.)

[ReadtheDocs](http://read-the-docs.readthedocs.org/) looks like an elegant solution for displaying the spec. However, it doesn't support comments directly. It can be used with Disqus; maybe that's acceptable. Other suggestions welcome.

**Comment by timgdavies** [comment]
@greggish Now that we are working on updates on GitHub - could you update the Google Doc to point here for all future contents?

I've removed links to the Google Doc from the current Readme files.

**Comment by greggish** [comment]
Doc is edited. However, I'm going to leave this issue open for now: I want to leave a link to the documentation on the website, once it's up via Read The Docs. And this is also a reminder to update the links to the documentation on the website (and in other materials) accordingly.

**Comment by timgdavies** [comment]
@greggish Ping as a reminder do make the changes to documentation links and then close this ticket.

**Comment by timgdavies** [comment]
In fact - as #94 covers updating the Google Doc, I'll close this one.
