### ISSUE TITLE
Updated schema and documentation generation

### ISSUE THREAD

**Issue by timgdavies** [openreferral/specification#99]
In preparation for the updated developer docs, I've been working through datapackage.json [on this branch](https://github.com/openreferral/specification/tree/updated-documentation) to:
- Add descriptions to each field
- Add constraints to each field

I'm taking the descriptions and constraints from [Appendix A of the specification](https://github.com/openreferral/specification/blob/updated-documentation/Human%20Services%20Data%20Specification%20%20v1.0.md#appendix-a) with only minor edits given the context of the descriptions.

This should provide the basis for @robredpath and colleagues to start working on auto-generated versions of the docs from the datapackage schema.

I'm making notes in [TODO.md](https://github.com/openreferral/specification/blob/updated-documentation/TODO.md) of issues arising, and things that the documentation around the schema will need to cover. 

I'm only 1/2 way through, but hopefully this should allow the docs generation work to get underway. 

Once we have done this, we may then want to review how far the schema created by combining the  current datapackage spec and Appendix A is consistent with the requirement of Ohana, and then from there to propose and 1.0.1 bug-fixes, or any 1.1 / version 2 issues.

**Comment by robredpath** [comment]
@timgdavies where are you up to with this at the moment? I'm just adding things to your branch as I go, but is it ready to merge from your point of view?

**Comment by timgdavies** [comment]
@robredpath I've not progressed since my last push, so if you want to merge please do go ahead.

**Comment by robredpath** [comment]
Thanks @timgdavies . To be clear on scope - this branch is fixing compliance with the Frictionless Data specs, moving existing docs into the schema (to a great enough extent for us to be able to start to autogenerate docs from them) and apply appropriate constraints that already exist in either schema or docs, correct? 

And thus, any issue that proposes to change any of those things (eg, add new constraints, rename things) is for an actual upgrade - eg 1.0.1 / 1.1 / 2.0?

**Comment by timgdavies** [comment]
That's correct. 

Only clear bug-fixes (e.g. missing foreign_key's) should go in this branch. All changes are for a future branch and process.

**Comment by robredpath** [comment]
Great, thanks :)

**Comment by timgdavies** [comment]
New docs now generating. Future work taking place on other issues.
